# Generated by Django 4.0.6 on 2022-07-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_employee_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='created_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='date_created',
        ),
    ]
