# Generated by Django 4.0.6 on 2022-07-24 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_created_date_employee_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='store_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employee_store', to='shop.location'),
        ),
    ]
