# Generated by Django 4.0.6 on 2022-08-10 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_payment_date_created_alter_payment_payment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='store_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='employee_store', to='shop.location'),
        ),
    ]
