# Generated by Django 4.0.6 on 2022-08-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_employee_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_ref',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='store_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_store', to='shop.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
