# Generated by Django 4.0.6 on 2022-08-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_category_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='store_location',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_store', to='shop.location'),
        ),
    ]
