# Generated by Django 4.0.6 on 2022-10-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_alter_employee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_ref',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
