# Generated by Django 4.0.6 on 2022-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_employee_id_alter_employee_employee_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_ref',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
