# Generated by Django 4.0.6 on 2022-11-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_role_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
    ]
